---
apiVersion: v2
name: namespacerole-operator
description:
  A Kubernetes operator that manages the role-based access control (RBAC) for
  namespaces
type: application
version: 0.2.3
appVersion: v0.2.0
